### ISSUE TITLE
Problem with publishing views.

### ISSUE THREAD

**Issue by Burans** [takepart-media/statamic-oreos#9] opened 2022-10-05 18:26 UTC
Hey!

I'm trying to implement Oreos and ran into an issue.
When I run `php artisan vendor:publish --tag=oreos-views` the popup gets published but the form does not.

I get an error:
`Can't locate path: </mysite/vendor/takepart-media/statamic-oreos/src/../resources/views/form.antlers.php>` .
Seems like it's looking for the file in the wrong place?

Cause I see the form file in `/vendor/takepart-media/statamic-oreos/resources/views/` right next to the popup file.

Statamic version: 3.2.38

Thanks!

**Comment by Web02Altitude** [comment] 2022-10-12 17:22
There is an update on the file that has not yet been applied to the publish script.
You can manually publish(copy) `form.antlers.html` instead of `form.antlers.php`

**Comment by eminos** [comment] 2022-12-20 10:25
How is this closed as completed? The issue is still there.

**Comment by markverg** [comment] 2022-12-21 13:50
agreed, just checked.. needs fixing

**Closed as completed** 2022-12-21 14:54 UTC
